
spring:
  profiles:
    active: dev1
---
spring:
  profiles: dev1
  application:
    name: service-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
   compression:
    request:
      enabled: true
      mime-type: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
   client: 
     config: 
        service-ribbon:  # 这里指定的是 @FeignClient 的 name/value 属性的值
          connectTimeout: 5000  # 链接超时时间
          readTimeout: 5000 # 读超时
          loggerLevel: full # 日志级别
        # errorDecoder: # 错误解码器（类路径）
        # retryer: com.feign.server.config.SimpleRetryer # 重试机制（类路径）建议不开启
        # requestInterceptors: 拦截器配置方式 一：多个拦截器， 需要注意如果有多个拦截器，"-" 不能少
          # - Intecerptor1 类路径，
          # - Interceptpt2 类路径
        # requestInterceptors: 拦截器配置方式 二：多个拦截器，用 [Interceptor, Interceptor] 配置，需要配置类路径
        # decode404: false 是否 404 解码
        # encoder： 编码器（类路径）
        # decoder： 解码器（类路径）
  
        
server:
  port: 8701
  
logging:
  level:
    com.feign.server.service.IFeignService: debug